In [7]:
import cv2
import numpy as np

# Görüntüyü Açma ve Kaydetme İşlemi

In [8]:
image=cv2.imread('DataCV2/image1.png')
print(image)

[[[ 24  82  81]
  [ 56 117 116]
  [ 67 130 129]
  ...
  [ 31  31  31]
  [ 31  31  31]
  [ 31  31  31]]

 [[ 38 101  94]
  [ 63 130 123]
  [ 71 139 131]
  ...
  [ 31  31  31]
  [ 31  31  31]
  [ 31  31  31]]

 [[ 72 138 127]
  [ 76 147 136]
  [ 68 139 128]
  ...
  [ 31  31  31]
  [ 31  31  31]
  [ 31  31  31]]

 ...

 [[167 188 216]
  [197 217 248]
  [211 231 255]
  ...
  [ 31  31  31]
  [ 31  31  31]
  [ 31  31  31]]

 [[176 193 219]
  [198 218 245]
  [210 231 255]
  ...
  [ 31  31  31]
  [ 31  31  31]
  [ 31  31  31]]

 [[136 150 187]
  [149 167 207]
  [152 174 214]
  ...
  [ 31  31  31]
  [ 31  31  31]
  [ 31  31  31]]]


In [9]:
cv2.imshow('image',image)
cv2.waitKey(0)

-1

In [10]:
cv2.destroyAllWindows()

In [11]:
cv2.imwrite('new_image.png',image) #kaydetme

True

# Kaydedilen Görüntüdeki Pikselleri Ekrana Yazdırma

In [12]:
first_local=image[0:10,0:10]
print(first_local)

[[[ 24  82  81]
  [ 56 117 116]
  [ 67 130 129]
  [ 64 134 132]
  [ 56 131 127]
  [ 67 139 134]
  [ 77 141 136]
  [ 97 159 153]
  [104 172 163]
  [105 178 169]]

 [[ 38 101  94]
  [ 63 130 123]
  [ 71 139 131]
  [ 77 149 140]
  [ 70 140 132]
  [ 59 122 115]
  [ 77 133 127]
  [ 92 150 144]
  [ 78 144 136]
  [ 77 149 141]]

 [[ 72 138 127]
  [ 76 147 136]
  [ 68 139 128]
  [ 83 153 141]
  [ 90 153 144]
  [ 88 143 137]
  [100 152 146]
  [114 169 165]
  [ 92 155 150]
  [ 69 139 132]]

 [[ 75 144 133]
  [ 77 153 140]
  [ 78 153 140]
  [ 74 144 132]
  [ 70 132 123]
  [ 79 134 128]
  [107 160 158]
  [ 90 147 146]
  [ 84 144 145]
  [103 166 163]]

 [[ 67 140 129]
  [ 68 150 137]
  [ 87 168 155]
  [ 67 144 132]
  [ 69 138 129]
  [ 80 146 140]
  [110 174 173]
  [ 98 160 163]
  [109 169 175]
  [125 184 183]]

 [[ 71 148 136]
  [ 68 153 141]
  [ 70 158 145]
  [ 62 146 135]
  [ 69 148 140]
  [ 74 152 147]
  [ 75 150 149]
  [ 77 146 152]
  [ 98 161 171]
  [104 161 162]]

 [[ 64 143 132]
  [ 72 157 1

In [13]:
pixel=image[100,200]
print(pixel) #belli kısmın piksellerini yazdırma işlemi

[ 93 161 149]


# 400x400 Boyutlarında Rastgele 0..255 Arasında Piksel Değerleri Olan Görüntüyü Elde Etme

In [14]:
image2=np.random.randint(0,256,size=(400,400,3),dtype=np.uint8)

In [39]:
piks=np.array([255,128,0], dtype=np.uint8) #kırmızı yeşil mavi

In [15]:
cv2.imshow("random_image",image2)
cv2.waitKey(0)

-1

In [16]:
cv2.imwrite("random_image.png",image2) #kaydetme işlemi

True

In [17]:
random_image=cv2.imread("random_image.png")
image=cv2.imread('DataCV2/image1.png')
#ikisini de okudum

In [18]:
random_image=cv2.resize(random_image,(image.shape[1],image.shape[0]))#boyutlar eşitleme

# Elde Edilen Görüntü ve Kaydedilen Görüntüyü Birleştirme

In [19]:
combine_image=cv2.hconcat([random_image,image])
#yatayda birleştirme

In [20]:
cv2.imshow('combined image',combine_image)#resmi göster
cv2.waitKey(0)
cv2.destroyAllWindows()