In [2]:
import cv2
import numpy as np

In [3]:
#Resmi yükleme işlemi
image=cv2.imread('DataCV2/gradient.png')
print(image)

[[[ 78  44  38]
  [ 78  44  38]
  [ 78  44  38]
  ...
  [ 63  39 129]
  [ 62  40 129]
  [ 63  41 130]]

 [[ 78  44  38]
  [ 78  44  38]
  [ 78  44  38]
  ...
  [ 64  40 129]
  [ 63  41 129]
  [ 63  41 130]]

 [[ 78  44  38]
  [ 78  44  38]
  [ 78  44  38]
  ...
  [ 64  40 129]
  [ 63  41 130]
  [ 63  41 130]]

 ...

 [[ 49  14  24]
  [ 49  14  24]
  [ 49  14  24]
  ...
  [114 162 240]
  [114 162 240]
  [114 162 240]]

 [[ 49  14  24]
  [ 49  14  24]
  [ 49  14  24]
  ...
  [114 162 240]
  [114 162 240]
  [115 162 241]]

 [[ 49  14  24]
  [ 49  14  24]
  [ 49  14  24]
  ...
  [114 162 240]
  [114 163 241]
  [114 163 241]]]


In [4]:
cv2.imshow('image',image)
cv2.waitKey(0)

-1

In [5]:
# Resmimizi gri tonlamalı olarak yükleyin
image1=cv2.imread('DataCV2/gradient.png',0)
print(image1)

[[ 46  46  46 ...  82  82  84]
 [ 46  46  46 ...  82  82  84]
 [ 46  46  46 ...  82  84  84]
 ...
 [ 21  21  21 ... 186 186 186]
 [ 21  21  21 ... 186 186 186]
 [ 21  21  21 ... 186 186 186]]


In [6]:
cv2.imshow('Original', image1)
cv2.waitKey(0) #gri hal gösterildi

-1

In [7]:
# 127'nin altındaki değerler 0'a gider (siyah, üstündeki her şey 255'e (beyaz) gider)
ret,thresh1 = cv2.threshold(image1, 127, 255, cv2.THRESH_BINARY)
cv2.imshow('1 Threshold Binary', thresh1) 
cv2.waitKey(0)

-1

In [7]:
# 127'nin altındaki değerler 255'e ve 127'nin üzerindeki değerler 0'a gider (yukarıdakinin tersi)
ret,thresh2 = cv2.threshold(image1, 127, 255, cv2.THRESH_BINARY_INV)
cv2.imshow('2 Threshold Binary Inverse', thresh2)
cv2.waitKey(0)

-1

In [8]:
# 127'nin üzerindeki değerler 127'de kesilir (tutulur) (255 argümanı kullanılmaz)
ret,thresh3 = cv2.threshold(image1, 127, 255, cv2.THRESH_TRUNC)
cv2.imshow('3 THRESH TRUNC', thresh3)
cv2.waitKey(0) #127'nin üzerindeki değerler 127'de kesilir

-1

In [9]:
# 127'nin altındaki değerler 0'a gider, 127'nin üzerindeki değerler değişmez
ret,thresh4 = cv2.threshold(image1, 127, 255, cv2.THRESH_TOZERO)
cv2.imshow('4 THRESH TOZERO', thresh4)
cv2.waitKey(0)

-1

In [10]:
# Yukarıyı yedekle, 127'nin altı değişmez, 127'nin üstü 0'a gider
ret,thresh5 = cv2.threshold(image1, 127, 255, cv2.THRESH_TOZERO_INV)
cv2.imshow('5 THRESH TOZERO INV', thresh5)
cv2.waitKey(0) 


-1

# Eşiklemeden daha iyi bir yol var mı?

Bu basit eşik yöntemlerinin en büyük dezavantajı, eşik değerini (yani daha önce kullandığımız 127 değeri) sağlamamız gerektiğidir.


Ya bunu yapmanın daha akıllıca bir yolu olsaydı?


Var, Uyarlanabilir eşikleme....


In [11]:
#Yeni bir resim yükleyelim
image2 = cv2.imread('DataCV2/Origin_of_Species.jpg', 0)
print(image2)


[[60 52 42 ... 20 17 15]
 [58 45 41 ... 19 18 17]
 [55 38 43 ... 20 20 20]
 ...
 [83 65 39 ... 92 93 93]
 [70 81 46 ... 93 89 84]
 [64 94 49 ... 22 15  4]]


In [12]:
cv2.imshow('Original', image2)
cv2.waitKey(0) 

-1

In [13]:
# 127'nin altındaki değerler 0'a gider (siyah, üstündeki her şey 255'e (beyaz) gider)
ret,thresh1 = cv2.threshold(image2, 127, 255, cv2.THRESH_BINARY)
cv2.imshow('Threshold Binary', thresh1)
cv2.waitKey(0) 

-1

In [14]:
# Gürültüyü ortadan kaldırdığı için görüntüleri bulanıklaştırmak iyi bir uygulamadır
image2 = cv2.GaussianBlur(image2, (3, 3), 0)
cv2.imshow("gürültü", image2) 
cv2.waitKey(0)

-1

In [16]:
# adaptiveThreshold'u kullanma
thresh = cv2.adaptiveThreshold(image2, 255, cv2.ADAPTIVE_THRESH_MEAN_C, 
                               cv2.THRESH_BINARY, 3, 5) 
cv2.imshow("Adaptive Mean Thresholding", thresh) 
cv2.waitKey(0)

-1

In [17]:
_, th2 = cv2.threshold(image2, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
cv2.imshow("Otsu's Thresholding", thresh) 
cv2.waitKey(0) 

-1

In [18]:
# Otsu'nun Gauss filtrelemesinden sonraki eşiği
blur = cv2.GaussianBlur(image2, (5,5), 0)
_, th3 = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
cv2.imshow("Guassian Otsu's Thresholding", thresh) 
cv2.waitKey(0) 

-1

In [19]:
import cv2

# Görüntüyü yükle
img = cv2.imread('DataCV2/image2.png')

# Görüntüyü bulanıklaştır
blur = cv2.GaussianBlur(img, (5, 5), 0)

# Görüntüyü göster
cv2.imshow('Original Image', img)
cv2.imshow('Blurred Image', blur)

# Bekle
cv2.waitKey(0)
cv2.destroyAllWindows()
